### ISSUE TITLE
corruption image size

### ISSUE THREAD

**Issue by amirhamidihd** [facebookresearch/augmentation-corruption#4]
I want to test your corruption and build a C_bar dataset on my own dataset, my image size is XxY and X,Y are different, 
How can I use your corruption code?

I have seen in gen_noise class power, phases and center_freq are getting a self.image input. this parameter is static and I want to make this dynamic, is there any solution o solve this?

Thanks

**Comment by ericmintun** [comment]
Our own experiments required that the exact same corruption be applicable to multiple random images sampled from the dataset, so the resolution needed to be fixed and known in advance. If you are just interested in randomly sampling independent corruption and image pairs, it is likely sufficient to modify the code to use a size obtained from the input image instead of the statically set self.im_size.
